language: scala
scala:
  - 2.11.4
jdk:
 - openjdk6
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
